# Generated by Django 5.1.2 on 2025-02-11 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicial', models.DateTimeField()),
                ('data_hora_chegada', models.DateTimeField(blank=True, null=True)),
                ('data_hora_final', models.DateTimeField(blank=True, null=True)),
                ('km_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('km_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('km_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('km_excedente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hora_excedente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('franquia_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_hora_excedente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('km_franquia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_km_excedente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedagio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prestador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestadores05', to='formacompanhamento.prestadores')),
                ('registro_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentes2', to='formacompanhamento.registropagamento')),
            ],
        ),
    ]
