# Generated by Django 5.1.2 on 2025-02-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0002_agente'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropagamento',
            name='hora_total1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='hora_total2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='hora_total3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
