# Generated by Django 5.1.6 on 2025-02-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0003_registropagamento_hora_total1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropagamento',
            name='motivo',
            field=models.CharField(blank=True, choices=[('ANTENISTA', 'ANTENISTA'), ('ACOMPANHAMENTO', 'ACOMPANHAMENTO'), ('PRESERVAÇÃO', 'PRESERVAÇÃO')], max_length=50, null=True),
        ),
    ]
