# Generated by Django 5.1.6 on 2025-02-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0005_prestadores_servicos_prestadores_valor_antenista_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestadores',
            old_name='franquia_hora',
            new_name='franquia_hora_antenista',
        ),
        migrations.RenameField(
            model_name='prestadores',
            old_name='valorh',
            new_name='franquia_hora_armado',
        ),
        migrations.RenameField(
            model_name='prestadores',
            old_name='valorkm',
            new_name='franquia_hora_desarmado',
        ),
        migrations.RemoveField(
            model_name='registropagamento',
            name='tipo',
        ),
        migrations.AddField(
            model_name='prestadores',
            name='franquia_km_antenista',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='prestadores',
            name='franquia_km_armado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='prestadores',
            name='franquia_km_desarmado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='prestadores',
            name='valorh_antenista',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='prestadores',
            name='valorh_armado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='prestadores',
            name='valorh_desarmado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='prestadores',
            name='valorkm_antenista',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='prestadores',
            name='valorkm_armado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='prestadores',
            name='valorkm_desarmado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='motivo1',
            field=models.CharField(blank=True, choices=[('Antenista', 'Antenista'), ('Antenista e Pronta Resposta Armado', 'Antenista e Pronta Resposta Armado'), ('Antenista e Pronta Resposta Desarmado', 'Antenista e Pronta Resposta Desarmado'), ('Pronta Resposta Armado e Pronta Resposta Desarmado', 'Antenista e Pronta Resposta Desarmado')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='motivo2',
            field=models.CharField(blank=True, choices=[('Antenista', 'Antenista'), ('Antenista e Pronta Resposta Armado', 'Antenista e Pronta Resposta Armado'), ('Antenista e Pronta Resposta Desarmado', 'Antenista e Pronta Resposta Desarmado'), ('Pronta Resposta Armado e Pronta Resposta Desarmado', 'Antenista e Pronta Resposta Desarmado')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='motivo3',
            field=models.CharField(blank=True, choices=[('Antenista', 'Antenista'), ('Antenista e Pronta Resposta Armado', 'Antenista e Pronta Resposta Armado'), ('Antenista e Pronta Resposta Desarmado', 'Antenista e Pronta Resposta Desarmado'), ('Pronta Resposta Armado e Pronta Resposta Desarmado', 'Antenista e Pronta Resposta Desarmado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prestadores',
            name='servicos',
            field=models.CharField(blank=True, choices=[('Antenista', 'Antenista'), ('Ponta Resposta Armado', 'Ponta Resposta Armado'), ('Pronta Resposta Desarmado', 'Pronta Resposta Desarmado'), ('Todos os serviços', ' Todos os servicos'), ('Antenista e Pronta Resposta Armado', 'Antenista e Pronta Resposta Armado'), ('Antenista e Pronta Resposta Desrmado', 'Antenista e Pronta Resposta Desrmado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='motivo',
            field=models.CharField(blank=True, choices=[('Antenista', 'Antenista'), ('Antenista e Pronta Resposta Armado', 'Antenista e Pronta Resposta Armado'), ('Antenista e Pronta Resposta Desarmado', 'Antenista e Pronta Resposta Desarmado'), ('Pronta Resposta Armado e Pronta Resposta Desarmado', 'Antenista e Pronta Resposta Desarmado')], max_length=50, null=True),
        ),
    ]
