# Generated by Django 5.1.6 on 2025-02-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0006_rename_franquia_hora_prestadores_franquia_hora_antenista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registropagamento',
            name='motivo',
            field=models.CharField(blank=True, choices=[('Antenista', 'Antenista'), ('Antenista e Pronta Resposta Armado', 'Antenista e Pronta Resposta Armado'), ('Antenista e Pronta Resposta Desarmado', 'Antenista e Pronta Resposta Desarmado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='motivo1',
            field=models.CharField(blank=True, choices=[('Antenista', 'Antenista'), ('Antenista e Pronta Resposta Armado', 'Antenista e Pronta Resposta Armado'), ('Antenista e Pronta Resposta Desarmado', 'Antenista e Pronta Resposta Desarmado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='motivo2',
            field=models.CharField(blank=True, choices=[('Antenista', 'Antenista'), ('Antenista e Pronta Resposta Armado', 'Antenista e Pronta Resposta Armado'), ('Antenista e Pronta Resposta Desarmado', 'Antenista e Pronta Resposta Desarmado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='motivo3',
            field=models.CharField(blank=True, choices=[('Antenista', 'Antenista'), ('Antenista e Pronta Resposta Armado', 'Antenista e Pronta Resposta Armado'), ('Antenista e Pronta Resposta Desarmado', 'Antenista e Pronta Resposta Desarmado')], max_length=50, null=True),
        ),
    ]
