# Generated by Django 5.1.6 on 2025-02-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0008_alter_registropagamento_motivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes_acionamento',
            name='franquiahora',
        ),
        migrations.RemoveField(
            model_name='clientes_acionamento',
            name='franquiakm',
        ),
        migrations.RemoveField(
            model_name='clientes_acionamento',
            name='valor_hora',
        ),
        migrations.RemoveField(
            model_name='clientes_acionamento',
            name='valor_km',
        ),
        migrations.RemoveField(
            model_name='clientes_acionamento',
            name='valordeacionamento',
        ),
        migrations.AddField(
            model_name='clientes_acionamento',
            name='agencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes_acionamento',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes_acionamento',
            name='cnpj',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes_acionamento',
            name='conta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes_acionamento',
            name='franquia_hora_antenista',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientes_acionamento',
            name='franquia_hora_armado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientes_acionamento',
            name='franquia_hora_desarmado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientes_acionamento',
            name='franquia_km_antenista',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientes_acionamento',
            name='franquia_km_armado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientes_acionamento',
            name='franquia_km_desarmado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientes_acionamento',
            name='servicos',
            field=models.CharField(blank=True, choices=[('Antenista', 'Antenista'), ('Ponta Resposta Armado', 'Ponta Resposta Armado'), ('Pronta Resposta Desarmado', 'Pronta Resposta Desarmado'), ('Todos os serviços', ' Todos os servicos'), ('Antenista e Pronta Resposta Armado', 'Antenista e Pronta Resposta Armado'), ('Antenista e Pronta Resposta Desrmado', 'Antenista e Pronta Resposta Desrmado')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientes_acionamento',
            name='telefone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes_acionamento',
            name='valor_antenista',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientes_acionamento',
            name='valor_prontaresposta_armado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientes_acionamento',
            name='valor_prontaresposta_desarmado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientes_acionamento',
            name='valorh_antenista',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientes_acionamento',
            name='valorh_armado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientes_acionamento',
            name='valorh_desarmado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientes_acionamento',
            name='valorkm_antenista',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientes_acionamento',
            name='valorkm_armado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientes_acionamento',
            name='valorkm_desarmado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
