# Generated by Django 5.1.6 on 2025-02-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0009_remove_clientes_acionamento_franquiahora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes_acionamento',
            name='servicos',
            field=models.CharField(blank=True, choices=[('Antenista', 'Antenista'), ('Ponta Resposta Armado', 'Ponta Resposta Armado'), ('Pronta Resposta Desarmado', 'Pronta Resposta Desarmado'), ('Todos os serviços', ' Todos os servicos')], max_length=50, null=True),
        ),
    ]
