# Generated by Django 5.1.4 on 2025-02-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0010_alter_clientes_acionamento_servicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestadores',
            name='vencimento_cnh',
            field=models.DateField(blank=True, null=True),
        ),
    ]
