# Generated by Django 5.1.4 on 2025-02-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0011_alter_prestadores_vencimento_cnh'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropagamento',
            name='endereco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
