# Generated by Django 5.1.2 on 2025-03-05 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0013_alter_clientes_acionamento_franquia_hora_antenista_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestadores',
            old_name='regiao_atuacao',
            new_name='lat_long',
        ),
    ]
