# Generated by Django 5.1.2 on 2025-03-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0014_rename_regiao_atuacao_prestadores_lat_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropagamento',
            name='tipo_servicos',
            field=models.CharField(blank=True, choices=[('Roubo', 'Roubo'), ('Preservação', 'Preservação')], max_length=50, null=True),
        ),
    ]
