# Generated by Django 5.1.2 on 2025-03-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0015_registropagamento_tipo_servicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestadores',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prestadores',
            name='estado',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('PA', 'Pará'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('TO', 'Tocantins'), ('AL', 'Alagoas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('MA', 'Maranhão'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RN', 'Rio Grande do Norte'), ('SE', 'Sergipe'), ('DF', 'Distrito Federal'), ('GO', 'Goiás'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('ES', 'Espírito Santo'), ('MG', 'Minas Gerais'), ('RJ', 'Rio de Janeiro'), ('SP', 'São Paulo'), ('PR', 'Paraná'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem17',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem18',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem19',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem20',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem21',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem22',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem23',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem24',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem25',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem26',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem27',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem28',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem29',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem30',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem31',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem32',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem33',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem34',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem35',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem36',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem37',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem38',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem39',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem40',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem41',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem42',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem43',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem44',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem45',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
    ]
