# Generated by Django 5.1.2 on 2025-03-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0016_prestadores_cidade_prestadores_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes_acionamento',
            name='atividade_principal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes_acionamento',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes_acionamento',
            name='estado',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('PA', 'Pará'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('TO', 'Tocantins'), ('AL', 'Alagoas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('MA', 'Maranhão'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RN', 'Rio Grande do Norte'), ('SE', 'Sergipe'), ('DF', 'Distrito Federal'), ('GO', 'Goiás'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('ES', 'Espírito Santo'), ('MG', 'Minas Gerais'), ('RJ', 'Rio de Janeiro'), ('SP', 'São Paulo'), ('PR', 'Paraná'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes_acionamento',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes_acionamento',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes_acionamento',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes_acionamento',
            name='razao_social',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes_acionamento',
            name='representante_legal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
