# Generated by Django 5.1.2 on 2025-03-20 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0018_clientes_acionamento_data_de_fechamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes_acionamento',
            name='contrato_pdf',
            field=models.FileField(blank=True, help_text='Faça upload do PDF do Contrato, se houver.', null=True, upload_to='contratos_pdf/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AddField(
            model_name='clientes_acionamento',
            name='proposta_pdf',
            field=models.FileField(blank=True, help_text='Faça upload do PDF da Proposta, se houver.', null=True, upload_to='propostas_pdf/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
