# Generated by Django 5.1.2 on 2025-03-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0021_clientes_acionamento_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes_acionamento',
            name='cep',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
