# Generated by Django 5.1.2 on 2025-03-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0022_clientes_acionamento_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes_acionamento',
            name='dias_a_faturar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
