# Generated by Django 5.1.2 on 2025-03-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0023_clientes_acionamento_dias_a_faturar'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes_acionamento',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes_acionamento',
            name='email_financeiro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes_acionamento',
            name='email_legal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes_acionamento',
            name='email_operacional',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
