# Generated by Django 5.1.2 on 2025-03-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0024_clientes_acionamento_cpf_cnpj_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registropagamento',
            old_name='placas',
            new_name='placas1',
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='placas2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='placas3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
