# Generated by Django 5.1.2 on 2025-03-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0025_rename_placas_registropagamento_placas1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropagamento',
            name='total_agentes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
