# Generated by Django 5.1.2 on 2025-03-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0027_remove_registropagamento_total_agentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropagamento',
            name='total_CLIENTE',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
