# Generated by Django 5.1.2 on 2025-03-31 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0028_registropagamento_total_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registropagamento',
            name='total_CLIENTE',
        ),
    ]
