# Generated by Django 5.1.2 on 2025-04-26 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0029_remove_registropagamento_total_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OcorrenciaTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportadora', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=8)),
                ('carreta', models.CharField(blank=True, max_length=8, null=True)),
                ('motorista', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('telefone', models.CharField(max_length=15)),
                ('local', models.CharField(max_length=255)),
                ('endereco', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('tipo_ocorrencia', models.CharField(choices=[('acidente', 'Acidente'), ('pane', 'Pane Mecânica'), ('roubo', 'Roubo/Furto'), ('atraso', 'Atraso'), ('outros', 'Outros')], max_length=20)),
                ('data_hora_ocorrencia', models.DateTimeField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ocorrência de Transporte',
                'verbose_name_plural': 'Ocorrências de Transporte',
                'ordering': ['-data_hora_ocorrencia'],
            },
        ),
    ]
