# Generated by Django 5.1.2 on 2025-04-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0030_ocorrenciatransporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrenciatransporte',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrenciatransporte',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
