# Generated by Django 5.1.2 on 2025-04-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0031_alter_ocorrenciatransporte_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrenciatransporte',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrenciatransporte',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
    ]
