# Generated by Django 5.1.2 on 2025-04-26 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0032_alter_ocorrenciatransporte_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrenciatransporte',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrenciatransporte',
            name='data_hora_ocorrencia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrenciatransporte',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrenciatransporte',
            name='local',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrenciatransporte',
            name='motorista',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrenciatransporte',
            name='placa',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrenciatransporte',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrenciatransporte',
            name='tipo_ocorrencia',
            field=models.CharField(blank=True, choices=[('acidente', 'Acidente'), ('pane', 'Pane Mecânica'), ('roubo', 'Roubo/Furto'), ('atraso', 'Atraso'), ('outros', 'Outros')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrenciatransporte',
            name='transportadora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrenciatransporte',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
