# Generated by Django 5.2.3 on 2025-08-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0033_alter_ocorrenciatransporte_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registropagamento',
            name='tipo_servicos',
            field=models.CharField(blank=True, choices=[('Roubo', 'Roubo'), ('Preservação', 'Preservação'), ('Esporadico', 'Esporadico')], max_length=50, null=True),
        ),
    ]
