# Generated by Django 5.1.2 on 2025-04-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_notifications', '0002_alter_notification_options_notification_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.AlterField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Visualizado'),
        ),
    ]
