# Generated by Django 5.2.3 on 2025-08-22 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Esporadico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_central', models.CharField(max_length=255)),
                ('data_acionamento', models.DateTimeField(auto_now=True)),
                ('km_inicial', models.IntegerField(blank=True, null=True)),
                ('foto_inicial', models.ImageField(blank=True, null=True, upload_to='fotos_esporadicos/')),
                ('km_final', models.IntegerField(blank=True, null=True)),
                ('fotos_final', models.ImageField(blank=True, null=True, upload_to='fotos_esporadicos/')),
                ('local_acionamento', models.CharField(blank=True, max_length=255, null=True)),
                ('foto_local_acionamento', models.ImageField(blank=True, null=True, upload_to='fotos_esporadicos/')),
            ],
        ),
        migrations.CreateModel(
            name='FotoEsporadico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos_esporadicos/')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('acionamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='esporadico.esporadico')),
            ],
        ),
    ]
