# Generated by Django 5.2.3 on 2025-08-22 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esporadico', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FotoEsporadico',
        ),
    ]
