# Generated by Django 5.2.3 on 2025-08-22 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esporadico', '0002_delete_fotoesporadico'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoEsporadico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos_esporadicos/adicionais/')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('esporadico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_adicionais', to='esporadico.esporadico')),
            ],
            options={
                'verbose_name': 'Foto Adicional',
                'verbose_name_plural': 'Fotos Adicionais',
                'ordering': ['data_upload'],
            },
        ),
    ]
