# Generated by Django 5.2.3 on 2025-08-22 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esporadico', '0003_fotoesporadico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='esporadico',
            options={'ordering': ['-data_acionamento'], 'verbose_name': 'Acionamento Esporádico', 'verbose_name_plural': 'Acionamentos Esporádicos'},
        ),
        migrations.RemoveField(
            model_name='esporadico',
            name='foto_local_acionamento',
        ),
        migrations.RemoveField(
            model_name='esporadico',
            name='fotos_final',
        ),
    ]
