# Generated by Django 5.2.3 on 2025-08-22 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esporadico', '0004_alter_esporadico_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='esporadico',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esporadicos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
    ]
