# Generated by Django 5.2.3 on 2025-08-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esporadico', '0005_esporadico_criado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='esporadico',
            name='hora_final',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Final'),
        ),
        migrations.AddField(
            model_name='esporadico',
            name='hora_inicial',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Inicial'),
        ),
        migrations.AddField(
            model_name='esporadico',
            name='valor_atribuido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Atribuído'),
        ),
    ]
