# Generated by Django 5.2.3 on 2025-08-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esporadico', '0006_esporadico_hora_final_esporadico_hora_inicial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esporadico',
            name='valor_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Calculado'),
        ),
    ]
