# Generated by Django 5.2.3 on 2025-08-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esporadico', '0007_esporadico_valor_calculado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esporadico',
            name='data_acionamento',
            field=models.DateTimeField(auto_now=True, verbose_name='Data e Hora do Acionamento'),
        ),
    ]
