# Generated by Django 5.2.3 on 2025-08-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esporadico', '0008_alter_esporadico_data_acionamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esporadico',
            name='data_acionamento',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora do Acionamento'),
        ),
    ]
